### ISSUE TITLE
Heroku (Item could not be created) Error

### ISSUE THREAD

**Issue by danielk0101** [sentanos/ProxyService#6] opened 2022-02-05 07:34 UTC
![image](https://user-images.githubusercontent.com/99068805/152633118-806352a4-728e-47d6-9af1-f6b8d4a57d6b.png)
It shows me that error sadly :(

**Comment by sentanos** [comment] 2022-02-06 00:44
Duplicate of #2

**Closed as completed by sentanos** 2022-02-06 00:44 UTC

**Comment by Hyderite** [comment] 2022-03-03 01:29
Actually, there is a way to fix that error! Check out this youtube video: https://www.youtube.com/watch?v=WFlOJ5dBTNk
